-- MySQL Script generated by MySQL Workbench
-- Tue May  4 20:46:18 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Imuniza
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Imuniza
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Imuniza` DEFAULT CHARACTER SET utf8 ;
USE `Imuniza` ;

-- -----------------------------------------------------
-- Table `Imuniza`.`Estado_Civil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Imuniza`.`Estado_Civil` (
  `idEstadoCivil` INT NOT NULL,
  `EstadoCivil` VARCHAR(45) NULL,
  PRIMARY KEY (`idEstadoCivil`));

INSERT INTO Estado_Civil(idEstadoCivil, EstadoCivil) VALUES ('1', 'Solteiro');

-- -----------------------------------------------------
-- Table `Imuniza`.`Escolaridade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Imuniza`.`Escolaridade` (
  `idEscolaridade` INT NOT NULL,
  `grauEscolaridade` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idEscolaridade`));

INSERT INTO Escolaridade(idEscolaridade, grauEscolaridade) VALUES ('1', 'Ensino Medio');

-- -----------------------------------------------------
-- Table `Imuniza`.`Plano_Saude`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Imuniza`.`Plano_Saude` (
  `idPlano` INT NOT NULL,
  `descricaoPlano` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idPlano`));

INSERT INTO Plano_Saude(idPlano, descricaoPlano) VALUES ('1', 'Unimed');
-- -----------------------------------------------------
-- Table `Imuniza`.`Religiao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Imuniza`.`Religiao` (
  `idReligiao` INT NOT NULL,
  `descReligiao` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idReligiao`));

INSERT INTO Religiao(idReligiao, descReligiao) VALUES ('1', 'Catolico');

-- -----------------------------------------------------
-- Table `Imuniza`.`Sensiveis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Imuniza`.`Sensiveis` (
  `idSensiveis` INT NOT NULL,
  `Raca` VARCHAR(45) NULL,
  `Cor` VARCHAR(45) NULL,
  `Etnia` VARCHAR(45) NULL,
  PRIMARY KEY (`idSensiveis`));

INSERT INTO Sensiveis(idSensiveis, Raca, Cor, Etnia) VALUES ('1', 'nao sei o que e', 'nao sei o que e', 'nao sei o que e');

-- -----------------------------------------------------
-- Table `Imuniza`.`Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Imuniza`.`Pessoa` (
  `idPessoa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `nascimento` DATE NOT NULL,
  `nome_mae` VARCHAR(45) NOT NULL,
  `cadastro_sus` CHAR(15) NOT NULL,
  `sexo_genetico` CHAR NOT NULL,
  `cpf` CHAR(11) NOT NULL,
  `alergias` TINYTEXT NULL,
  `idEstadoCivil` INT,
  `idEscolaridade` INT,
  `idPlanoSaude` INT,
  `idReligiao` INT,
  `idSensiveis` INT,
  `rua` VARCHAR(60) NOT NULL,
  `numeroRua` INT NOT NULL,
  `municipio` VARCHAR(60) NOT NULL,
  `estado` VARCHAR(60) NOT NULL,
  `cep` CHAR(8) NOT NULL,
  PRIMARY KEY (`idPessoa`),
  CONSTRAINT `EstadoCivilFK`
    FOREIGN KEY (`idEstadoCivil`)
    REFERENCES `Imuniza`.`Estado_Civil` (`idEstadoCivil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `EscolaridadeFK`
    FOREIGN KEY (`idEscolaridade`)
    REFERENCES `Imuniza`.`Escolaridade` (`idEscolaridade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PlanoSaudeFK`
    FOREIGN KEY (`idPlanoSaude`)
    REFERENCES `Imuniza`.`Plano_Saude` (`idPlano`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ReligiaoFK`
    FOREIGN KEY (`idReligiao`)
    REFERENCES `Imuniza`.`Religiao` (`idReligiao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `EtniaFK`
    FOREIGN KEY (`idSensiveis`)
    REFERENCES `Imuniza`.`Sensiveis` (`idSensiveis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Imuniza`.`Doenca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Imuniza`.`Doenca` (
  `idDoenca` INT NOT NULL,
  `codigoDoenca` VARCHAR(45) NOT NULL,
  `descDoenca` VARCHAR(60) NOT NULL,
  `sintomas` TEXT NULL,
  PRIMARY KEY (`idDoenca`));


-- -----------------------------------------------------
-- Table `Imuniza`.`Vacina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Imuniza`.`Vacina` (
  `idVacina` INT NOT NULL,
  `codVacina` VARCHAR(60) NOT NULL,
  `lote` VARCHAR(45) NULL,
  `doses` INT NOT NULL,
  `dataFabricacao` DATE NOT NULL,
  `efeitosColaterais` TEXT NOT NULL,
  `infoArmazenagem` TEXT NOT NULL,
  `viaAdministracao` TINYTEXT NOT NULL,
  `idDoenca` INT NOT NULL,
  PRIMARY KEY (`idVacina`),
  CONSTRAINT `DoencaFK`
    FOREIGN KEY (`idDoenca`)
    REFERENCES `Imuniza`.`Doenca` (`idDoenca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Imuniza`.`Pessoa_Vacina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Imuniza`.`Pessoa_Vacina` (
  `idVacina` INT NOT NULL,
  `idPessoa` INT NOT NULL,
  `dose` INT NOT NULL,
  `dataDose` DATE NOT NULL,
  PRIMARY KEY (`idVacina`),
  CONSTRAINT `VacinaFK`
    FOREIGN KEY (`idVacina`)
    REFERENCES `Imuniza`.`Vacina` (`idVacina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PessoaFK`
    FOREIGN KEY (`idPessoa`)
    REFERENCES `Imuniza`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INDEX `DoencaFK_idx` (`idDoenca` ASC) VISIBLE,

INDEX `PessoaFK_idx` (`idPessoa` ASC) VISIBLE,

  INDEX `EstadoCivil_idx` (`idEstadoCivil` ASC) VISIBLE,
  INDEX `EscolaridadeFK_idx` (`idEscolaridade` ASC) VISIBLE,
  INDEX `PlanoSaudeFK_idx` (`idPlanoSaude` ASC) VISIBLE,
  INDEX `ReligiaoFK_idx` (`idReligiao` ASC) VISIBLE,
  INDEX `RacaFK_idx` (`idSensiveis` ASC) VISIBLE,
  INDEX `Nome_idx` (`nome` ASC) VISIBLE,